/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.GameScene {
    export class GameTipUI extends Scene {
		public tipBg:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameScene/GameTip");
        }
    }
    export class LoadSceneUI extends Scene {
		public loading:Laya.Sprite;
		public logo:Laya.Sprite;
		public hethTip:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameScene/LoadScene");
        }
    }
}